{
 "title": "Gatling Test - Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "API_min",
    "label": "Min_RT",
    "query": {
     "query": "metrics(gatling_ukaf_end_to_end_(.*)_all_min)"
    }
   },
   {
    "name": "API_max",
    "label": "Max_RT",
    "query": {
     "query": "metrics(gatling_ukaf_end_to_end_(.*)_all_max)"
    }
   },
   {
    "name": "API_avg",
    "query": {
     "query": "metrics(gatling_ukaf_end_to_end_(.*)_all_mean)"
    }
   },
   {
    "name": "UserCount",
    "label": "ActiveUser",
    "query": {
     "query": "metrics(gatling_ukaf_end_to_end_(.*)_active)"
    }
   },
   {
    "name": "95th_RT",
    "label": "95th_RT",
    "query": {
     "query": "metrics(gatling_ukaf_end_to_end_(.*)_all_percentiles95)"
    }
   },
   {
    "name": "Errors",
    "label": "Errors",
    "query": {
     "query": "metrics(gatling_ukaf_end_to_end_(.*)_ko_c)"
    }
   },
   {
    "name": "Throughput",
    "label": "Throughput",
    "query": {
     "query": "metrics(gatling_ukaf_end_to_end_(.*)_ok_count)"
    }
   },
   {
    "name": "99th_RT",
    "label": "99th_RT",
    "query": {
     "query": "metrics(gatling_ukaf_end_to_end_(.*)_all_percentiles99)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Min Response Time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    { "expr": "$API_min", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Avg Response Time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "$API_avg", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Max Response Time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "$API_max", "legendFormat": "__auto" }
   ]
  },
  {
   "title": " Successful Request",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "gatling_ukaf_end_to_end_UKAF_EndToEnd_01_HomePage_POST__access_getAccessInfo_ok_count",
     "legendFormat": "01_HomePage_POST__access_getAccessInfo"
    },
    {
     "expr": "gatling_ukaf_end_to_end_UKAF_EndToEnd_01_HomePage_POST__auth_getToken_ok_count",
     "legendFormat": "01_HomePage_POST__auth_getToken"
    },
    {
     "expr": "gatling_ukaf_end_to_end_UKAF_EndToEnd_01_HomePage_POST__elasticsearch_search_ok_count",
     "legendFormat": "01_HomePage_POST__elasticsearch_search"
    },
    {
     "expr": "gatling_ukaf_end_to_end_UKAF_EndToEnd_01_HomePage_POST__elasticsearch_search_ok_count",
     "legendFormat": "01_HomePage_POST__elasticsearch_search"
    },
    {
     "expr": "gatling_ukaf_end_to_end_UKAF_EndToEnd_02_InsertWorkbook_POST__auth_getToken_ok_count",
     "legendFormat": "02_InsertWorkbook_POST__auth_getToken"
    },
    {
     "expr": "gatling_ukaf_end_to_end_UKAF_EndToEnd_02_InsertWorkbook_POST__elasticsearch_insertDoc_ok_count",
     "legendFormat": "02_InsertWorkbook_POST__elasticsearch_insertDoc"
    },
    {
     "expr": "gatling_ukaf_end_to_end_UKAF_EndToEnd_02_InsertWorkbook_POST__elasticsearch_sheet_insertDoc_ok_count",
     "legendFormat": "02_InsertWorkbook_POST__elasticsearch_sheet_insertDoc"
    },
    {
     "expr": "gatling_ukaf_end_to_end_UKAF_EndToEnd_02_InsertWorkbook_POST__elasticsearch_sheet_searchByWorkbookId_ok_count",
     "legendFormat": "02_InsertWorkbook_POST__elasticsearch_sheet_searchByWorkbookId"
    },
    {
     "expr": "gatling_ukaf_end_to_end_UKAF_EndToEnd_02_InsertWorkbook_POST__elasticsearch_sheetrow_searchBySheetId_ok_count",
     "legendFormat": "02_InsertWorkbook_POST__elasticsearch_sheetrow_searchBySheetId"
    },
    {
     "expr": "gatling_ukaf_end_to_end_UKAF_EndToEnd_03_UpdateWorkbook_PATCH__elasticsearch_update_ok_count",
     "legendFormat": "03_UpdateWorkbook_PATCH__elasticsearch_update"
    },
    {
     "expr": "gatling_ukaf_end_to_end_UKAF_EndToEnd_03_UpdateWorkbook_POST__auth_getToken_ok_count",
     "legendFormat": "03_UpdateWorkbook_POST__auth_getToken"
    },
    {
     "expr": "gatling_ukaf_end_to_end_UKAF_EndToEnd_03_UpdateWorkbook_POST__elasticsearch_insertDoc_ok_count",
     "legendFormat": "03_UpdateWorkbook_POST__elasticsearch_insertDoc"
    },
    {
     "expr": "gatling_ukaf_end_to_end_UKAF_EndToEnd_04_UpdateSheet_POST__auth_getToken_ok_count",
     "legendFormat": "04_UpdateSheet_POST__auth_getToken"
    },
    {
     "expr": "gatling_ukaf_end_to_end_UKAF_EndToEnd_04_UpdateSheet_POST__elasticsearch_insertDoc_ok_count",
     "legendFormat": "04_UpdateSheet_POST__elasticsearch_insertDoc"
    },
    {
     "expr": "gatling_ukaf_end_to_end_UKAF_EndToEnd_04_UpdateSheet_POST__elasticsearch_sheet_insertDoc_ok_count",
     "legendFormat": "04_UpdateSheet_POST__elasticsearch_sheet_insertDoc"
    },
    {
     "expr": "gatling_ukaf_end_to_end_UKAF_EndToEnd_05_DeleteSheet_POST__auth_getToken_ok_count",
     "legendFormat": "05_DeleteSheet_POST__auth_getToken"
    },
    {
     "expr": "gatling_ukaf_end_to_end_UKAF_EndToEnd_05_DeleteSheet_POST__elasticsearch_insertDoc_ok_count",
     "legendFormat": "05_DeleteSheet_POST__elasticsearch_insertDoc"
    },
    {
     "expr": "gatling_ukaf_end_to_end_UKAF_EndToEnd_05_DeleteSheet_POST__elasticsearch_sheet_delete_ok_count",
     "legendFormat": "05_DeleteSheet_POST__elasticsearch_sheet_delete"
    },
    {
     "expr": "gatling_ukaf_end_to_end_UKAF_EndToEnd_05_DeleteSheet_POST__elasticsearch_sheet_insertDoc_ok_count",
     "legendFormat": "05_DeleteSheet_POST__elasticsearch_sheet_insertDoc"
    },
    {
     "expr": "gatling_ukaf_end_to_end_UKAF_EndToEnd_06_DeleteWorkbook_PATCH__elasticsearch_workbook_delete_ok_count",
     "legendFormat": "06_DeleteWorkbook_PATCH__elasticsearch_workbook_delete"
    },
    {
     "expr": "gatling_ukaf_end_to_end_UKAF_EndToEnd_06_DeleteWorkbook_POST__auth_getToken_ok_count",
     "legendFormat": "06_DeleteWorkbook_POST__auth_getToken"
    },
    {
     "expr": "gatling_ukaf_end_to_end_UKAF_EndToEnd_06_DeleteWorkbook_POST__elasticsearch_insertDoc_ok_count",
     "legendFormat": "06_DeleteWorkbook_POST__elasticsearch_insertDoc"
    }
   ]
  },
  {
   "title": "Failed Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "gatling_ukaf_end_to_end_allRequests_ko_count\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "$UserCount", "legendFormat": "{{Concurrent Users}}" }
   ]
  },
  {
   "title": "Performance Test - Summary",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "gatling_ukaf_end_to_end_users_allUsers_active",
     "legendFormat": "Users"
    },
    {
     "expr": "gatling_ukaf_end_to_end_allRequests_ok_count",
     "legendFormat": "Samples"
    },
    {
     "expr": "gatling_ukaf_end_to_end_allRequests_ko_count",
     "legendFormat": "Failed"
    },
    {
     "expr": "gatling_ukaf_end_to_end_allRequests_all_max",
     "legendFormat": "Max"
    },
    {
     "expr": "gatling_ukaf_end_to_end_allRequests_all_mean",
     "legendFormat": "Avg"
    },
    {
     "expr": "gatling_ukaf_end_to_end_allRequests_all_min",
     "legendFormat": "Min"
    },
    {
     "expr": "gatling_ukaf_end_to_end_allRequests_all_percentiles50",
     "legendFormat": "50th"
    },
    {
     "expr": "gatling_ukaf_end_to_end_allRequests_all_percentiles75th",
     "legendFormat": "75th"
    },
    {
     "expr": "gatling_ukaf_end_to_end_allRequests_all_percentiles95",
     "legendFormat": "95th"
    },
    {
     "expr": "gatling_ukaf_end_to_end_allRequests_all_percentiles99",
     "legendFormat": "99th"
    },
    {
     "expr": "gatling_ukaf_end_to_end_allRequests_all_stdDev",
     "legendFormat": "stdDev"
    }
   ]
  },
  {
   "title": "AVG Response Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "$API_avg", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "AVG RT VS 95th Percentile VS 99th Percentile",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "$API_avg", "legendFormat": "{{AVG Response Time}}" },
    { "expr": "$95th_RT", "legendFormat": "{{95th Percentile}}" },
    { "expr": "$99th_RT", "legendFormat": "{{99th Percentile}}" }
   ]
  },
  {
   "title": "Response time Distribution",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "$API_avg", "legendFormat": "__auto" },
    { "expr": "$95th_RT", "legendFormat": "__auto" },
    { "expr": "$99th_RT", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "ConcurrentUsers Vs Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    { "expr": "$UserCount", "legendFormat": "__auto" },
    { "expr": "$Throughput", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Users Vs 95th Percentile",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "$UserCount", "legendFormat": "__auto" },
    { "expr": "$95th_RT", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "99th Percentile",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "$99th_RT", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Throughput",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    { "expr": "$Throughput", "legendFormat": "Throughput" }
   ]
  },
  {
   "title": " Successful Request",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gatling_ukaf_end_to_end_UKAF_EndToEnd_01_HomePage_POST__access_getAccessInfo_ok_count",
     "legendFormat": "01_HomePage_POST__access_getAccessInfo"
    },
    {
     "expr": "gatling_ukaf_end_to_end_UKAF_EndToEnd_01_HomePage_POST__auth_getToken_ok_count",
     "legendFormat": "01_HomePage_POST__auth_getToken"
    },
    {
     "expr": "gatling_ukaf_end_to_end_UKAF_EndToEnd_01_HomePage_POST__elasticsearch_search_ok_count",
     "legendFormat": "01_HomePage_POST__elasticsearch_search"
    },
    {
     "expr": "gatling_ukaf_end_to_end_UKAF_EndToEnd_01_HomePage_POST__elasticsearch_search_ok_count",
     "legendFormat": "01_HomePage_POST__elasticsearch_search"
    },
    {
     "expr": "gatling_ukaf_end_to_end_UKAF_EndToEnd_02_InsertWorkbook_POST__auth_getToken_ok_count",
     "legendFormat": "02_InsertWorkbook_POST__auth_getToken"
    },
    {
     "expr": "gatling_ukaf_end_to_end_UKAF_EndToEnd_02_InsertWorkbook_POST__elasticsearch_insertDoc_ok_count",
     "legendFormat": "02_InsertWorkbook_POST__elasticsearch_insertDoc"
    },
    {
     "expr": "gatling_ukaf_end_to_end_UKAF_EndToEnd_02_InsertWorkbook_POST__elasticsearch_sheet_insertDoc_ok_count",
     "legendFormat": "02_InsertWorkbook_POST__elasticsearch_sheet_insertDoc"
    },
    {
     "expr": "gatling_ukaf_end_to_end_UKAF_EndToEnd_02_InsertWorkbook_POST__elasticsearch_sheet_searchByWorkbookId_ok_count",
     "legendFormat": "02_InsertWorkbook_POST__elasticsearch_sheet_searchByWorkbookId"
    },
    {
     "expr": "gatling_ukaf_end_to_end_UKAF_EndToEnd_02_InsertWorkbook_POST__elasticsearch_sheetrow_searchBySheetId_ok_count",
     "legendFormat": "02_InsertWorkbook_POST__elasticsearch_sheetrow_searchBySheetId"
    },
    {
     "expr": "gatling_ukaf_end_to_end_UKAF_EndToEnd_03_UpdateWorkbook_PATCH__elasticsearch_update_ok_count",
     "legendFormat": "03_UpdateWorkbook_PATCH__elasticsearch_update"
    },
    {
     "expr": "gatling_ukaf_end_to_end_UKAF_EndToEnd_03_UpdateWorkbook_POST__auth_getToken_ok_count",
     "legendFormat": "03_UpdateWorkbook_POST__auth_getToken"
    },
    {
     "expr": "gatling_ukaf_end_to_end_UKAF_EndToEnd_03_UpdateWorkbook_POST__elasticsearch_insertDoc_ok_count",
     "legendFormat": "03_UpdateWorkbook_POST__elasticsearch_insertDoc"
    },
    {
     "expr": "gatling_ukaf_end_to_end_UKAF_EndToEnd_04_UpdateSheet_POST__auth_getToken_ok_count",
     "legendFormat": "04_UpdateSheet_POST__auth_getToken"
    },
    {
     "expr": "gatling_ukaf_end_to_end_UKAF_EndToEnd_04_UpdateSheet_POST__elasticsearch_insertDoc_ok_count",
     "legendFormat": "04_UpdateSheet_POST__elasticsearch_insertDoc"
    },
    {
     "expr": "gatling_ukaf_end_to_end_UKAF_EndToEnd_04_UpdateSheet_POST__elasticsearch_sheet_insertDoc_ok_count",
     "legendFormat": "04_UpdateSheet_POST__elasticsearch_sheet_insertDoc"
    },
    {
     "expr": "gatling_ukaf_end_to_end_UKAF_EndToEnd_05_DeleteSheet_POST__auth_getToken_ok_count",
     "legendFormat": "05_DeleteSheet_POST__auth_getToken"
    },
    {
     "expr": "gatling_ukaf_end_to_end_UKAF_EndToEnd_05_DeleteSheet_POST__elasticsearch_insertDoc_ok_count",
     "legendFormat": "05_DeleteSheet_POST__elasticsearch_insertDoc"
    },
    {
     "expr": "gatling_ukaf_end_to_end_UKAF_EndToEnd_05_DeleteSheet_POST__elasticsearch_sheet_delete_ok_count",
     "legendFormat": "05_DeleteSheet_POST__elasticsearch_sheet_delete"
    },
    {
     "expr": "gatling_ukaf_end_to_end_UKAF_EndToEnd_05_DeleteSheet_POST__elasticsearch_sheet_insertDoc_ok_count",
     "legendFormat": "05_DeleteSheet_POST__elasticsearch_sheet_insertDoc"
    },
    {
     "expr": "gatling_ukaf_end_to_end_UKAF_EndToEnd_06_DeleteWorkbook_PATCH__elasticsearch_workbook_delete_ok_count",
     "legendFormat": "06_DeleteWorkbook_PATCH__elasticsearch_workbook_delete"
    },
    {
     "expr": "gatling_ukaf_end_to_end_UKAF_EndToEnd_06_DeleteWorkbook_POST__auth_getToken_ok_count",
     "legendFormat": "06_DeleteWorkbook_POST__auth_getToken"
    },
    {
     "expr": "gatling_ukaf_end_to_end_UKAF_EndToEnd_06_DeleteWorkbook_POST__elasticsearch_insertDoc_ok_count",
     "legendFormat": "06_DeleteWorkbook_POST__elasticsearch_insertDoc"
    }
   ]
  },
  {
   "title": " Failed Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "$Errors", "legendFormat": "__auto" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 101 },
   "options": {
    "content": "# Server Side Statistics (CPU, Memory, Disc, IO)\n#=================================================================\n\n"
   },
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System CPU Utlization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(node_cpu_seconds_total{instance=\"10.100.131.125:9100\", job=\"node_exporter\", mode=\"system\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((rate(node_cpu_seconds_total{instance=\"10.100.131.125:9100\", job=\"node_exporter\"}[$__rate_interval])))",
     "legendFormat": "System"
    }
   ]
  },
  {
   "title": "User CPU Utlization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(node_cpu_seconds_total{instance=\"10.100.131.125:9100\", job=\"node_exporter\", mode=\"user\"}[$__rate_interval])) / on(instance) sum by(instance) (rate(node_cpu_seconds_total{instance=\"10.100.131.125:9100\", job=\"node_exporter\"}[$__rate_interval]))",
     "legendFormat": "System"
    }
   ]
  },
  {
   "title": "CPU time spent in user and system contexts",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{instance=\"10.100.131.125:9100\",job=\"node_exporter\"}[$__rate_interval])",
     "legendFormat": "Time spent"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"10.100.131.125:9100\", job=\"node_exporter\"}",
     "legendFormat": "Total Memory"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"10.100.131.125:9100\",job=\"node_exporter\"} - node_memory_MemFree_bytes{instance=\"10.100.131.125:9100\",job=\"node_exporter\"} - (node_memory_Cached_bytes{instance=\"10.100.131.125:9100\",job=\"node_exporter\"} + node_memory_Buffers_bytes{instance=\"10.100.131.125:9100\",job=\"node_exporter\"} + node_memory_SReclaimable_bytes{instance=\"10.100.131.125:9100\",job=\"node_exporter\"})",
     "legendFormat": "Used Memory"
    }
   ]
  },
  {
   "title": "Avg Queue Size",
   "type": "timeseries",
   "description": "The average queue length of the requests that were issued to the device",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_weighted_seconds_total{instance=\"10.100.131.125:9100\",job=\"node_exporter\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Context Switch/ Interupts",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 160 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(node_context_switches_total{instance=\"10.100.131.125:9100\",job=\"node_exporter\"}[$__rate_interval])",
     "legendFormat": "Context switches"
    },
    {
     "expr": "irate(node_intr_total{instance=\"node_exporter:9100\",job=\"node_exporter\"}[$__rate_interval])",
     "legendFormat": "Interrupts"
    }
   ]
  },
  {
   "title": "Process schedule stats Running / Waiting",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 171 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(node_schedstat_running_seconds_total{instance=\"10.100.131.125:9100\",job=\"node_exporter\"}[$__rate_interval])",
     "legendFormat": "CPU {{ cpu }} - seconds spent running a process"
    },
    {
     "expr": "irate(node_schedstat_waiting_seconds_total{instance=\"node_exporter:9100\",job=\"node_exporter\"}[$__rate_interval])",
     "legendFormat": "CPU {{ cpu }} - seconds spent by processing waiting for this CPU"
    }
   ]
  },
  {
   "title": "Page Fault",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 182 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(node_vmstat_pgmajfault{instance=\"10.100.131.125:9100\",job=\"node_exporter\"}[$__rate_interval])",
     "legendFormat": "MajorPageFault"
    },
    {
     "expr": "irate(node_vmstat_pgfault{instance=\"10.100.131.125:9100\",job=\"node_exporter\"}[$__rate_interval])  - irate(node_vmstat_pgmajfault{instance=\"10.100.131.125:9100\",job=\"node_exporter\"}[$__rate_interval])",
     "legendFormat": "MinorPageFault"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 191 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"10.100.131.125:9100\",job=\"node_exporter\"}[$__rate_interval])*8",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"10.100.131.125:9100\",job=\"node_exporter\"}[$__rate_interval])*8",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "I/O Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 200 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{instance=\"10.100.131.125:9100\", job=\"node_exporter\", device=\"sdd\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}