{
 "title": "Logs",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "DAG AVG Execution Time",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate({job=\"airbyte\"}[$__auto])"
    }
   ]
  },
  {
   "title": "DAG Execution Time by Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate({job=\"airbyte\"}[$__auto])"
    }
   ]
  },
  {
   "title": "New Panel",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 18 },
   "targets": [
    {
     "expr": "{filename=\"/var/log/2024-03-28/Validate_all_operator_accounts.py.log\"}"
    }
   ]
  },
  {
   "title": "Full Log",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "{job=\"airbyte\"} |~ \"dict_keys\""
    }
   ]
  },
  {
   "title": "Full Log",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "{job=\"airbyte\"} |~ \"dict_keys\""
    }
   ]
  },
  {
   "title": "Full Log",
   "type": "logs",
   "gridPos": { "h": 25, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "{filename=~\"/var/log/2024-03-28/Mexos_execute_all_operator_accounts\\\\.py\\\\.log|/var/log/2024-03-28/Validate_all_operator_accounts\\\\.py\\\\.log\"} | logfmt --strict --keep-empty"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "{job=\"airbyte\"} |= `ERROR` | logfmt"
    }
   ]
  },
  {
   "title": "Warnings",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "{job=\"airbyte\"} |= `WARNING` | logfmt --strict --keep-empty"
    }
   ]
  }
 ]
}