{
 "title": "Graphite dashboard",
 "time": { "from": "2024-01-10T08:10:00.000Z", "to": "2024-01-10T08:41:37.000Z" },
 "templating": {
  "list": [
   {
    "name": "gatling",
    "label": "gatling",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Min Response Time",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "gatling.$gatling.allRequests.ok.min"
    }
   ]
  },
  {
   "title": "Avg Response Time",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "gatling.$gatling.allRequests.all.mean"
    }
   ]
  },
  {
   "title": "Max Response Time",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "gatling.$gatling.allRequests.all.max"
    }
   ]
  },
  {
   "title": "Concurrent Users",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "target": "gatling.$gatling.users.allUsers.active"
    }
   ]
  },
  {
   "title": "Avg Response Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "target": "gatling.$gatling.allRequests.*.mean"
    }
   ]
  },
  {
   "title": "95th Percentile",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "target": "gatling.$gatling.allRequests.*.percentiles95"
    }
   ]
  },
  {
   "title": "99th Percentile",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "target": "gatling.$gatling.allRequests.*.percentiles99"
    }
   ]
  },
  {
   "title": "99th Percentile",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "target": "gatling.$gatling.allRequests.*.percentiles99"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "target": "gatling.$gatling.allRequests.all.count"
    }
   ]
  },
  {
   "title": "Avg VS 95th Vs 99th",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "target": "gatling.$gatling.allRequests.all.mean"
    },
    {
     "target": "gatling.$gatling.allRequests.*.percentiles95"
    },
    {
     "target": "gatling.$gatling.allRequests.*.percentiles99"
    }
   ]
  },
  {
   "title": "Successful Request Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "gatling.$gatling.allRequests.ok.count"
    }
   ]
  },
  {
   "title": "Failed Request Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "gatling.$gatling.allRequests.ko.count"
    }
   ]
  }
 ]
}