{
 "title": "Automation Dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "query0", "label": "Date", "query": "Select date From Demo" }
  ]
 },
 "panels": [
  {
   "title": "Total Test",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "ukaf",
     "rawSql": "SELECT ScenarioCount FROM ukaf.demo LIMIT 50 "
    }
   ]
  },
  {
   "title": "Pass Test",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "ukaf",
     "rawSql": "SELECT PassedCount FROM ukaf.demo LIMIT 50 "
    }
   ]
  },
  {
   "title": "Failed Test",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "ukaf",
     "rawSql": "SELECT FailedCount FROM ukaf.demo LIMIT 50 "
    }
   ]
  },
  {
   "title": "Percentage Distribution",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "ukaf",
     "rawSql": "SELECT FailedCount FROM ukaf.demo LIMIT 50 "
    },
    {
     "dataset": "ukaf",
     "rawSql": "SELECT PassedCount FROM ukaf.demo LIMIT 50 "
    }
   ]
  },
  {
   "title": "Feature File Execution Time",
   "type": "barchart",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dataset": "ukaf",
     "rawSql": "SELECT FeatureName, DurationMillis FROM ukaf.demo LIMIT 50 "
    }
   ]
  },
  {
   "title": "Test Execution Count by Time",
   "type": "histogram",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "dataset": "ukaf",
     "rawSql": "SELECT FeatureName, DurationMillis FROM ukaf.demo LIMIT 50 "
    }
   ]
  },
  {
   "title": "Test Execution Details",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "dataset": "ukaf",
     "rawSql": "SELECT FeatureName, PassedCount, FailedCount, FailedStatus, ScenarioCount, DurationMillis FROM ukaf.demo LIMIT 50 "
    }
   ]
  },
  {
   "title": "Successful Test Count By Date",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {
     "dataset": "ukaf",
     "rawSql": "SELECT Date, SUM(PassedCount) FROM ukaf.demo GROUP BY Date LIMIT 50 "
    }
   ]
  },
  {
   "title": "Failed Test Count By Date",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 70 },
   "targets": [
    {
     "dataset": "ukaf",
     "rawSql": "SELECT Date, SUM(FailedCount) FROM ukaf.demo GROUP BY Date LIMIT 50 "
    }
   ]
  },
  {
   "title": "DB Stats",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 81 },
   "targets": [
    {
     "dataset": "sys",
     "rawSql": "SELECT * FROM sys.host_summary LIMIT 50 "
    }
   ]
  },
  {
   "title": "DB Stats",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 91 },
   "targets": [
    {
     "dataset": "performance_schema",
     "rawSql": "SELECT * FROM performance_schema.events_transactions_history LIMIT 50 "
    }
   ]
  }
 ]
}