{
 "title": "Jenkins Dashboard",
 "description": "Jobs queue speeds and rates, Executors availability, Nodes status, Jenkins and JVM resource usage.",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Job Execution Time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "default_jenkins_builds_build_duration_milliseconds{jenkins=\"TCB_DE_PT2_DEMO\"}"
    }
   ]
  },
  {
   "title": "Build STATUS",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(default_jenkins_builds_build_result{instance=\"host.docker.internal:8084\", status=\"FAILURE\"})"
    },
    {
     "expr": "count(default_jenkins_builds_build_result{instance=\"host.docker.internal:8084\", status=\"SUCCESS\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(default_jenkins_builds_build_result{instance=\"host.docker.internal:8084\", status=\"ABORTED\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Build duration",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "default_jenkins_builds_build_duration_milliseconds{number!=\"1\"}"
    }
   ]
  },
  {
   "title": "Total Successful Build Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(default_jenkins_builds_build_result{buildable=\"true\", status=\"SUCCESS\"})"
    }
   ]
  },
  {
   "title": "Total Failed Build Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(default_jenkins_builds_build_result{buildable=\"true\", status=\"FAILURE\"})"
    }
   ]
  },
  {
   "title": "Processing speed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(jenkins_task_buildable_duration{instance=\"host.docker.internal:8084\"}[1m])"
    }
   ]
  },
  {
   "title": "Job queue duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(jenkins_job_queuing_duration{job=\"Jenkins\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Jenkins Build health",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "default_jenkins_builds_health_score{instance=\"host.docker.internal:8084\", buildable=\"true\"}"
    }
   ]
  },
  {
   "title": "JVM free memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(vm_memory_total_used{instance=\"host.docker.internal:8084\"} * 100) / vm_memory_total_max{instance=\"host.docker.internal:8084\"}"
    }
   ]
  },
  {
   "title": "Executor In-use",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "jenkins_executor_in_use_value{job=\"Jenkins\"}"
    }
   ]
  },
  {
   "title": "Executor free",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "jenkins_executor_free_value{job=\"Jenkins\"}"
    }
   ]
  },
  {
   "title": "JVM uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vm_uptime_milliseconds{instance=\"host.docker.internal:8084\"}"
    }
   ]
  },
  {
   "title": "BuildDuration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(jenkins_job_building_duration{job=\"Jenkins\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Build STATUS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(default_jenkins_builds_build_result{instance=\"host.docker.internal:8084\", status=\"FAILURE\"})"
    },
    {
     "expr": "count(default_jenkins_builds_build_result{instance=\"host.docker.internal:8084\", status=\"SUCCESS\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(default_jenkins_builds_build_result{instance=\"host.docker.internal:8084\", status=\"ABORTED\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jenkins nodes offline",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jenkins_node_offline_value{job=\"Jenkins\"}"
    }
   ]
  },
  {
   "title": "Jenkins queue size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "jenkins_queue_size_value{job=\"Jenkins\"}"
    }
   ]
  },
  {
   "title": "Queued rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(jenkins_job_queuing_duration_count{instance=\"host.docker.internal:8084\"}[1m])"
    }
   ]
  },
  {
   "title": "CPUusage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "vm_cpu_load{job=\"Jenkins\"}"
    }
   ]
  },
  {
   "title": "JVM Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{job=\"Jenkins\"}"
    }
   ]
  }
 ]
}